apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: ecr-reader
      containers:
        - name: backend
          image: 016311861830.dkr.ecr.us-east-1.amazonaws.com/dev/ecom-backend
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-env
          env: 
            valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
        
