apiVersion: ENC[AES256_GCM,data:lPQ=,iv:k1pAIGmngvZQpXslqdg02Io9Oholwhf0Iqu0vjxYd7s=,tag:XfTPAraplSgisH3wYfsqtg==,type:str]
kind: ENC[AES256_GCM,data:AA7xRKLX,iv:irT0z1PTWesi4mtD2rdZsTmKvmGYGKgIAsj2/kAJmtA=,tag:T6EElhvUZL5O0gqOLSur6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7ACeT3sQ5fPksw==,iv:DRdUUlJYt2na2ybpp9fK+0tApIKfBvxavwwnBOYwtNM=,tag:iAgZShia8gB2dSMhCwG3Lw==,type:str]
    namespace: ENC[AES256_GCM,data:B1GBQ/Zquw==,iv:53V/CuKGqKprJxZsmM2mBoarx77sr68UA5U81R0n3vo=,tag:3yz6YXCEJlErD7FMtyJs7w==,type:str]
type: ENC[AES256_GCM,data:xYcr51fW,iv:JFOXLe73Id/y/pIV/8FziLjbR39TIx+S6IgOzc85jmQ=,tag:71c+r6l5OFj701kaYPLhDQ==,type:str]
stringData:
    JWT_KEY: ENC[AES256_GCM,data:kL4O23pzAFpebtc=,iv:P3qs6s3CVb1uC06j9hxVmhJpQHVIzvxD4cqqdmU+iUI=,tag:yQCSO5j6aYLZYl//CF5XVw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:016311861830:key/319cd819-54a3-4238-ae16-4265ce0148c8
          created_at: "2025-07-28T08:12:40Z"
          enc: AQICAHg8pSIEEqJGTAqg/ryXE02udhDWjaKoFKL66IYHSHGktgH+J8pbqy252yF7E3Mt7eVNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDJLR38ZNqCU46HnZAgEQgDsqSKctrJrK51Urq6sZe6FFCv5a64LdI1poSBqvhyu3//eyythXaVqMFRWPEkBW1aAULG0Xdm9WRPiOEQ==
          aws_profile: ""
    lastmodified: "2025-07-28T08:12:41Z"
    mac: ENC[AES256_GCM,data:fnWn2E0rasLyVT0osLRaL2tJ6bucJRBcLi22skiaad6cbgELZJB+yvzqQuUQQ6T4qpGDi5RK/GAJZ/XJOOpYzirPVVVrK2lxI46faCz927ZPgXbwVA5iK9vsKWPJ+zXBrvL1c/Spwt/AlXFX2g+AZhtf5+nUAvMt0kot4nCxx7E=,iv:UPts3cFsZdyVyPd0nXkAa3wXiUwMG4XTMrpoCRGWntQ=,tag:vl0747Ty5pg80Hhulbx7fQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
