resources:
 - ../../../base/ecom-backend

configMapGenerator:
  - name: backend-env
    envs:
      - .env

images:
- name: 016311861830.dkr.ecr.us-east-1.amazonaws.com/dev/ecom-backend
  newName: 016311861830.dkr.ecr.us-east-1.amazonaws.com/dev/ecom-backend
  newTag: a5ce28f