apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: ecr-reader
      containers:
        - name: frontend
          image: 016311861830.dkr.ecr.us-east-1.amazonaws.com/dev/ecom-frontend:latest
          ports:
            - containerPort: 5173 
          command: ["npm", "run", "dev", "--", "--host"]
          env:
            - name: VITE_BACKEND_URL
              value: http://3.239.59.47:31849

