apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: ecr-reader
      containers:
        - name: frontend
          image: 016311861830.dkr.ecr.us-east-1.amazonaws.com/dev/ecom-frontend:latest
          ports:
            - containerPort: 3000  
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://aa86d1069bcac4360a93d7228a8a7b70-1578860455.us-east-1.elb.amazonaws.com

